export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const SET_LOGIN_USER_ERROR = 'SET_LOGIN_USER_ERROR';
export const REMOVE_LOGIN_USER_ERROR = 'REMOVE_LOGIN_USER_ERROR';
